shlee322/delivery-tracker

README.md
apiserver/app.js
apiserver/package.json
apiserver/server.js
client/nuxt.config.js
client/package.json

Add NPM Package (delivery-tracker-apiserver, delivery-tracker-client)
The client is not ready yet.
refs: #7

Add NPM Package

---

apiserver/carriers/kr.lotte/index.js

kr.lotte - Fixed 500 errors when empty progresses

---

apiserver/carriers/kr.cway/index.js
apiserver/test/getTrack.js

kr.cway - Add Carrier

---

apiserver/carriers/kr.homepick/index.js

kr.homepick - Add Carrier

---

apiserver/carriers/kr.honamlogis/index.js

kr.honamlogis - Add Carrier

---

apiserver/carriers/kr.hdexp/index.js

kr.hdexp - Add Carrier

---

apiserver/carriers/kr.chunilps/index.js

kr.chunilps - Add Carrier

---

apiserver/carriers/kr.ilyanglogis/index.js

kr.ilyanglogis - Add Carrier

---

apiserver/carriers/kr.kdexp/index.js

kr.kdexp - Add Carrier

---

apiserver/carriers/kr.kunyoung/index.js

kr.kunyoung - Add Carrier

---

apiserver/carriers/de.dhl/index.js

de.dhl - Add Carrier

---

apiserver/carriers/kr.daesin/index.js

kr.daesin - Add Carrier

---

apiserver/carriers/un.upu.ems/index.js

un.upu.ems - Add Carrier

---

apiserver/carriers/us.fedex/index.js

us.fedex - Add Carrier

---

apiserver/carriers/us.ups/index.js

us.ups - Add Carrier

---

apiserver/carriers/us.usps/index.js

us.usps - Add Carrier

---

apiserver/carriers/nl.tnt/index.js

nl.tnt - Add Carrier

---

apiserver/carriers/kr.slx/index.js

kr.slx - Add Carrier

---

apiserver/carriers/kr.hanips/index.js

kr.hanips - Add Carrier

---

packages/apiserver/app.js
packages/apiserver/carriers/kr.hanips/index.js

* Bug fix
* Current Behavior - Bug
1. inconv error at kr.hanips/index.js
```javascript
const iconv = new Iconv('EUC-KR', 'UTF-8//TRANSLIT//IGNORE')();
^
TypeError: (intermediate value) is not a function
at Object.<anonymous> (/usr/src/app/carriers/kr.hanips/index.js:7:61)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at fs.readdirSync.forEach.name (/usr/src/app/app.js:14:22)
at Array.forEach (<anonymous>)
```
2. access object as if array at app.js
```javascript 
const CARRIERS_INFOS = CARRIERS.map(({ id, info }) => ({ id, ...info }));
^
TypeError: …
```

Fix apiserver/app bugs

---

packages/apiserver/app.js
packages/apiserver/carriers/jp.sagawa/index.js
packages/apiserver/carriers/jp.yamato/index.js
packages/apiserver/carriers/jp.yuubin/index.js
packages/apiserver/carriers/kr.hanips/index.js

* feature
* add new feature
1. [Kuroneko Yamato](http://toi.kuronekoyamato.co.jp/cgi-bin/tneko) 
```
/carriers/jp.yamato/tracks/443496171020
```
2. [Sagawa](http://k2k.sagawa-exp.co.jp/p/web/okurijosearch.do?okurijoNo=435075176056)
```
/carriers/jp.sagawa/tracks/435075176056
```
3. [Japan Post](https://trackings.post.japanpost.jp/services/srv/search/direct?reqCodeNo1=EG725089303JP&searchKind=S002&locale=ja)
```
/carriers/jp.yuubin/tracks/EG725089303JP
```
This branch also includes about the fix of apiserver/app bugs
Please merge the PR #60 before merging it

Add jp carriers

---

packages/apiserver/carriers/kr.logen/index.js

Fixed kr.logen

---

packages/apiserver/carriers/kr.epost/index.js

test: 6865109394355
shlee322/delivery-tracker#108

우체국 택배 조회 에러 수정

---

packages/apiserver/carriers/kr.epost/index.js

| Before | After |
|:---:|:---:|
| <img width="631" alt="before" src="https://user-images.githubusercontent.com/931655/204003208-f9c1642c-56ae-42da-bc4a-126cb6cd230b.png"> | <img width="332" alt="after" src="https://user-images.githubusercontent.com/931655/204003205-f62954c3-668b-4c43-b5ad-ff4a585bc2ab.png"> |

우체국 택배 시각을 잘못 불러오는 문제 해결

---

packages/apiserver/carriers/kr.cjlogistics/index.js

kr.cjlogistics: 배송 조회 에러 수정

---

packages/apiserver/carriers/kr.hanjin/index.js

kr.hanjin: fix empty tr bug
